### ISSUE TITLE
feat(healthcheck): Add helthcheck api for DefaultService

### ISSUE THREAD

**Issue by AlexCzar** [chrisgahlert/gradle-dcompose-plugin#26]
This is important for programmatic configuration of services in build-scripts.
When using
```kotlin
services.register("name") {
}
```
there should be an option to configure custom healthcheck, analogous to what following docker-compose.yml does:

```yaml
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tight5
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 3
```
Without this it is impossible to fully configure service programmatically.
